server:
  port: 18080
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: fwh-web
logging:
  file:
    path: /export/Logs
  config: classpath:logback-spring.xml